### ISSUE TITLE
Install payu locally 

### ISSUE THREAD

**Issue by nichannah** [marshallward/payu#105]
The payu code can change frequently and there is a dependency between payu code, model code and the experiment details/layout. 

It would be nice to be able to ship a version of payu with a particular model/experiment. 

This also has the benefit of allowing us to make reproducible experiments. Presently the experiment depends on the version of payu which itself will change over time. 

This also has the benefit of making experiments more self-contained in general.

**Comment by aekiss** [comment]
good idea - for example the 0.1deg won't run for payu<0.8.1

**Comment by marshallward** [comment]
While we could do this, I think it would be better to keep pypi up to date and make things compatible with local installations.

Also, if we really are dependent on custom versions, I feel like we have failed in a core goal.

**Comment by marshallward** [comment]
Having said that, I think we do need to make plans to get payu out of `/apps` and give users more control here, it is probably not a sustainable solution.

**Comment by aidanheerdegen** [comment]
How about an option for local installs?

Look for a `payu` directory inside the control directory and use that if it is found.

This would allow for bundling of an experiment (if the archive directory was a local dir and not a symlink).

It would also mean it would be possible for someone to easily run a custom `payu` if they needed to, and just delete or move their local `payu` directory when no longer required.

**Comment by aidanheerdegen** [comment]
The bundling option might also mean we can cater more easily for off-site users, or those without the expertise to replicate an HPC install.

**Comment by marshallward** [comment]
definitely thumpsup on local installs.  Should we rename this issue?

**Comment by aidanheerdegen** [comment]
Can if you want. @nicjhan seemed ok with the idea

**Comment by marshallward** [comment]
This appears to work now with the "dereversion" changes.
