### ISSUE TITLE
payu hang sweep

### ISSUE THREAD

**Issue by aekiss** [marshallward/payu#106]
Kial's suggestion in the COSIMA workshop: implement `payu hang sweep`.

I took this to mean a variant of `payu sweep` which would save appropriate crash/hang information for debugging, log the fault and/or send an alert to whoever might be in a position to investigate (eg NCI help), then do the usual sweep so the user could get on with running the model. 

So basically it's a way to streamline and organise crash/hang reporting and facilitate closer involvement of technical support people.

**Comment by marshallward** [comment]
So `sweep` already saves the logs and marks them with PBS job ID, which is nearly there.  I guess I would amend a flag here, e.g. `payu sweep --report`.

What should we do in this case?  Tar/zip the logs into a file?  Automatically email?

I also wonder if this is necessary.  If we know a crash hung, then we (presumably) know the job ID and can just say "here are the logs".

**Comment by marshallward** [comment]
@kialstewart did you want to add anything to this?

**Comment by marshallward** [comment]
My feeling is that this is already being done in `error_logs` and `pbs_logs`, and haven't heard any feedback since, so I'm going to close this.

Anyone who wants to add to it, feel free to re-open it.
