### ISSUE TITLE
Fix o2i.nc and i2o.nc permissions when copying into lab

### ISSUE THREAD

**Issue by nicjhan** [marshallward/payu#111]
The cice model tries to overwrite restarts that come from /short/public/accessom2/input but fails because these do not have write permissions by default. 

One fix may be for the payu CICE driver to modify file perms as it copies them over.

**Comment by marshallward** [comment]
Just checking, does it actually overwrite the value in the input directory?  Or does it, say, open the file from input and then save it to restart?

**Comment by nicjhan** [comment]
It saves it to RESTART and then chmod + overwrite that one.

**Comment by nicjhan** [comment]
Another (future) option would be to name each restart differently, similar to what CICE does. Then there would be no overwriting.
