### ISSUE TITLE
mom6 driver puts optional config files in the wrong location

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#118]
The optional config files in the mom6 driver:

```python
        # TODO: Need to figure out what's going on here with MOM6
        self.optional_config_files = [
            'data_table',
            'data_table.MOM6',
            'data_table.OM4',
            'data_table.SIS',
            'data_table.icebergs',

            'field_table',

            'MOM_override',
            'MOM_layout',
            'MOM_saltrestore',

            'SIS_input',
            'SIS_override',
            'SIS_layout',
        ]
```

Are copied to the `self.work_input_path`, which is `work/INPUT`.

https://github.com/marshallward/payu/blob/master/payu/models/model.py#L156

Which is not the correct location.

I can add these configs to `self.config_files` but they are not guaranteed to always be there. We can't change `self.work_input_path` to point to `work` as the input files that should be in `work/INPUT` are then in the wrong location.

I propose to create a new path, `self.work_opt_config_path` as the place to copy optional configs, and will make it default to `self.work_path` and alter it for `mom6`

**Comment by marshallward** [comment]
I've done a 0.9.1 update which reverts this change, and I've installed it on raijin.  Agreed that the concept needs to be revisited and improved.

If it's working then we can close this.

**Comment by aidanheerdegen** [comment]
Reverts what change?

**Comment by marshallward** [comment]
I had changed work_path to work_input_path but I've just reverted it.

**Comment by aidanheerdegen** [comment]
That line was last changed here:

https://github.com/marshallward/payu/commit/c990acda9e18a656f899cac0b6bbb75b22d6279e

Four years ago.

Are you sure this won't break anything? It seems it was intended for use with `mom` and things like `ocean_mask_table`, which I would argue aren't config files, but it is in the code, so someone might be using it I guess.

**Comment by marshallward** [comment]
I just changed it to work_input_path when I did the 0.9 release, and only did it to accommodate the mask tables.  But it was irresponsible and I've just reverted it.

I'm not sure what line you mean, but I'm basically putting it back the way it was a few days ago.

**Comment by aidanheerdegen** [comment]
Ah I see, okey doke. Thanks. I'll test it and let you know

**Comment by aidanheerdegen** [comment]
Seems ok. I'll close.
