### ISSUE TITLE
Runlog feature can't be turned off

### ISSUE THREAD

**Issue by nichannah** [marshallward/payu#137]
Adding 

runlog: False 

into the config.yaml does not turn off the runlog. The runlog if-test in experiment.py is not referring to the correct variable. 

This means, for example, that the --lab option not longer works because the runlog depends on payu being invoked from within a git repo. 

Perhaps the runlog should run git from within the config dir rather than the run dir.

**Comment by marshallward** [comment]
Confirmed, seems like the rewrite still has some problems, thanks.

**Comment by marshallward** [comment]
seems to fix things:
```
         if curdir:
             os.chdir(curdir)
 
-        if self.runlog:
+        if self.runlog.enabled:
             self.runlog.commit()
 
         f_out.close()
```

**Comment by marshallward** [comment]
Fixed in master, can you test it?

**Comment by nichannah** [comment]
Thanks! Was going to do it myself.

**Comment by marshallward** [comment]
You caught me in the middle of a frenzy :)

**Comment by marshallward** [comment]
gonna say this is fixed; feel free to open if still broken
