### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by nicjhan** [marshallward/payu#14]
Payu needs unit tests.

**Comment by aidanheerdegen** [comment]
If there is a 'dry-run' type mode where all commands are just echoed to stdout this could be a first step.

Does this mean there should be a sub-process wrapper where this can be turned on/off, or should it be implemented with a dodgy monkey-punching approach?

For more rigorous testing, mock (and specifically flexmock) is probably required.

**Comment by marshallward** [comment]
There is a minimal framework for doing tests now.  (Only `mkdir_p` is tested at the moment.)

Let's close this and reopen new tickets for new tests.
