### ISSUE TITLE
MITgcm does not correctly support runlog

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#148]
MITgcm does not properly track config files in it's git repository when using runlog:
```
[aph502@raijin3 SOMs_v1_no_tides]$ pwd
/home/157/cjs157/payu/mitgcm/SOMs_v1_no_tides
[aph502@raijin3 SOMs_v1_no_tides]$ ls
archive      data      data.diagnostics  data.kpp  data.obcs  data.rbcs            eedata      mitgcm.err  readme
config.yaml  data.cal  data.exf          data.mnc  data.pkg   dz.copy_me_to_input  eedata.mth  mitgcm.out  work
[aph502@raijin3 SOMs_v1_no_tides]$ git ls-tree -r master --name-only
config.yaml
```
This is a major problem. People have been using runlog thinking it was tracking their experimental setup, and it has not.

It is because MITgcm adds config files in `setup` by matching files that start with `data`, but runlog is initialised in `init`

https://github.com/marshallward/payu/blob/4c15c888cd3faf0cc12963580874166341f2b2b2/payu/experiment.py#L92

Possible solutions would be to add all known `MITgcm` config paths to `optional_config_files`, or initialise runlog in `setup`.

**Comment by marshallward** [comment]
I think there's a general trend of abusing `__init__`, so happy to get things out of those functions and make things more explicit.

In this case, I'd say lets get `create_manifest` out if `Runlog.__init__()` and make it an explicit instruction in `experiment.setup()`

**Comment by marshallward** [comment]
this will probably also need changes in `push_cmd.py` and possibly `ghsetup_cmd.py`

**Comment by aidanheerdegen** [comment]
Whatever you think best @marshallward

**Comment by aidanheerdegen** [comment]
Thinking about it now, a first quick fix is to just move that code into `init`. Might be best , get the manifest stiff bedded down and the look at cleaning up driver interfaces?

In the meantime, is there value in putting some assert statements at certain points to make sure drivers have played by the unwritten rules?

**Comment by marshallward** [comment]
move `self.runlog = Runlog()` into `Experiment.__init__`?  I don't understand what code needs to be moved.  I thought the problem was that Mitgcm did not know what its config files were until `setup`?

**Comment by marshallward** [comment]
Applied the change to master: cc4b91564784ba06fb9c3512fe25131d031e7251

I've tested a MOM5 and MITgcm run and both seem to work OK.

**Comment by aidanheerdegen** [comment]
Sorry, I wasn't clear. I meant move the MITgcm config file stuff into it's init method, but no matter.

Sounds like this is fine, so no biggie. I'm a bit skeptical of the MITgcm globbing thing though. Could end up with all sorts of rubbish in the Git repo. Do we have a canonical list of all possible names for these files? If not, could we try opening them as namelists and only add them if they parse ok? Even then could have old rubbishy stuff like `eedata.backup` which people have a habit of making as they're not used to having stuff under version control

**Comment by marshallward** [comment]
I agree it would be nice to have a stricter whitelist, I'm not a fan either of the generated list.

I remember trying to address this long ago, but my 2012 self found it too challenging.  It would be nice to have another crack at it.

I think the truth is that MITgcm has been off my (and your?) radar for so long that it hasn't gotten much attention.

**Comment by aidanheerdegen** [comment]
Had a brief chat with Callum and most packages have their own namelist file which is called `data.<packagename>`, but he is also pretty sure there are actual data files that begin with `data.`. 

My proposal would be to get a list of all files that match `data.*` and `ee*`, and try and open each as a namelist file, and add them if they are parseable as namelists.

Will `f90nml` correctly barf on binary files and such?

**Comment by marshallward** [comment]
Often `f90nml` will just produce an empty namelist when trying to parse a non-namelist file.  This is (unfortunately) by design, since a valid namelist can have literally anything inbetween the actual namelist groups.

I suppose you could try parsing them, and if it's an empty namelist, then it's not a namelist?
