### ISSUE TITLE
Multiple executables in manifest, all symlinked into work

### ISSUE THREAD

**Issue by marshallward** [marshallward/payu#164]
If I change my executable throughout my run, then it seems that new entries are added to `manifest/exe.yaml`.  This may be intentional, I'm not sure at this point.  But a further consequence is that each one of these files gets symlinked into the work directory.

I don't know if this is really a problem, since the correct executable is still used (perhaps still using the absolute path to the original?) but it is confusing.

**Comment by marshallward** [comment]
To follow on this, inputs seem to "remember" their manifests and ignore changes to `config.yaml`.

Specifically, if an input directory is removed, then the manifest still seems to continue to load in the files from the removed directory, presumably because they are present in the manifests.  If I delete the manifests, then the input directory list is respected.

This may be a fluke if my dev version, will try to confirm in stock version later tonight.

**Comment by aidanheerdegen** [comment]
That is a feature, not a bug. All this is up for discussion/change. I wanted to be able to delete the input dir and make a config that was more resistant to change for things like access-om2 and COSIMA. I thought this would make it better/easier for @nichannah

**Comment by marshallward** [comment]
Yeah, sounds like this will need a discussion, probably on Monday.

**Comment by aidanheerdegen** [comment]
There is a related issue with input files. Old inputs could hang around in manifests. The PR above solves this as well. Input files that no longer appear in input paths are deleted unless `scaninputs` is set to `False`(it defaults to `True`):
```yaml
manifest:
    scaninputs: False
```

**Comment by aidanheerdegen** [comment]
With an existing `manifests/input.yaml` is `scaninputs` is `False` you can even delete the entry for the `input` directory for the model and it will just use the manifest. This could be super useful for people like @nichannah who distribute model configs, and me as it turns out with ACCESS-ESM configs.

**Comment by marshallward** [comment]
Sounds good to me.  Does this do the checksums?

**Comment by aidanheerdegen** [comment]
The exe manifest issue is solved by not loading the previous exe manifest and just creating a new one (unless we specify a reproduce run). The executables are generally not large so recalculating a few md5 hashes is not time consuming.

The input manifest issue is solved by saving the existing input manifest keys when an existing manifest is loaded and removing the key (work filepath) as they are found in the input dirs (the usual hash checks ate still done). When all the inputs have been traversed any keys remaining from the original list are removed from the input manifest.

The scenario above corresponds to scaninputs is True. 

There weren't many code changes to enable this.
