### ISSUE TITLE
MITgcm run start time option

### ISSUE THREAD

**Issue by strat123123** [marshallward/payu#169]
Currently, when running a model on MITgcm with Payu, it is not possible to change the time step after a few runs without problems. Each run creates an output and a restart folder. When the time step is changed for the next run, the input files for the boundary conditions begin at the wrong time. This is due to the start time of the model being calculated based on the current number of time steps and the size of the time step in the data file, as well as the number of output files (it looks at the number appended to the output file name). It is possible to solve this issue manually by setting a start time variable, but this has to be changed after each run, and so causes problems when running 'payu run -n number_of_runs'. It would be great if the 'Payu run' command had an option so that the start time would be set automatically. I talked with Aidan about this and he asked if I could create the issue here.

**Comment by marshallward** [comment]
Yes, I have some memory of that problem, and while I don't remember much about it, I had thought that we had made some progress in sorting it out.

It looks like we added something to support the `starttime` and `endtime` arguments to `data.nml.parm03` if `ntimesteps` is missing.  Is it possible to use those to define your runtimes?

If that isn't possible, then we could probably work something out to recalculate the timesteps and start times.

**Comment by aidanheerdegen** [comment]
Nic and Callum have been communicating with me about it. 

As Nic points out it is possible to manually set `starttime` but that doesn't work automatically once you've change timestep.

Callum's idea is to parse the STDOUT for the value of ... `runtime`? Can't recall exactly, but this is always correct, and tells us the current model time. This could be written to a yaml file, similar to the FMS models using `time_stamp.out`

@strat123123 can you point us towards a config directory with this issue?

**Comment by marshallward** [comment]
I recall our older shell scripts (written by Andy, I think) used to work out the equivalent number of nsteps after a timestep change, but I guess we decided not to include it in the current driver.

**Comment by strat123123** [comment]
@aidanheerdegen This is an example:

/home/156/nv3798/payu/mitgcm/SOMs_unforced_v1 

For the 11th run, the time step was set to 15 seconds. For subsequent runs, the variable starttime was set manually to be equal to model time, and the time step was set back to 30 seconds.

**Comment by strat123123** [comment]
This is a script that is currently used to compute the new start time after each run for the ///starttime/// variable:
///
#!/bin/bash
# Read in the current timestep of the data file, as well as the number of time
# steps and start_time. Then multiply the timestep by the number of timesteps,
# and add that to the start time.
tmp=$(grep starttime data | cut -d'"' -f2)
starttime=$(echo $tmp | tr -dc '0-9')

tmp=$(grep deltaT data | cut -d'"' -f2)
deltaT=$(echo $tmp | tr -dc '0-9')

tmp=$(grep ntimesteps data | cut -d'"' -f2)
ntimesteps=$(echo $tmp | tr -dc '0-9')

echo $starttime
echo $ntimesteps
echo $deltaT

new_start_time=$(($starttime+$ntimesteps*$deltaT))
sed -i -e 's/starttime='"$starttime"'/starttime='"$new_start_time"'/g' data
echo $new_start_time
///

**Comment by aidanheerdegen** [comment]
The new time handling logic tries to be as flexible as possible, but the recommended approach is to set `starttime`, `endtime` and `deltaT` (or whatever time steps you use) at the beginning of a simulation.

With this combination `payu` will determine the desired run length (`starttime` - `endtime`) and the number of iterations (by dividing the run length by `deltaT`). In this way changing the time step will keep the run length constant but change the number of iterations.

The actual `starttime` and `endtime` will always be recalculated and the namelist in `work/data` appropriately updated, but the values in the config file set the total runtime.

`payu` now also saves a `mitgcm.res.yaml` file in the `restart` directory which contains the `endtime` of that simulation, which is read in and used as the updated `starttime` of the next simulation.

There may be combinations of times/timesteps/number of iterations that will break this logic, but using the recommended approach above, and only every changing the tilmestep in the `data` file in the control directory should work correctly.
