### ISSUE TITLE
Expose archive as cli command

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#49]
Occasionally an error may occur at the end of a run, before the archive command has run. It would be great to be able to do:

```
payu archive
```

to do all the drudge work of cleaning up the outputs and restarts and putting them in the right places.

**Comment by marshallward** [comment]
This is pretty rare though and usually indicates an error somewhere else.

We can put it in easily, but wouldn't it be better to resolve the cases
where archival fails?

**Comment by aidanheerdegen** [comment]
I agree it is rare-ish, but I've had to manually archive a data set over a dozen times.

In a way it makes it easier to diagnose the problem, as the files are in the final form the user is familiar with.

If the run was broken then I the user has to delete the archived directories, which isn't onerous. 

I guess the biggest problem is if the archiving fails because there are problems with the outputs?

**Comment by marshallward** [comment]
Even if archival does fail for some cases, it sounds like it would be
useful, so might as well add it, even if only for debugging.
