### ISSUE TITLE
npersocket and npernode command line arguments no longer work on raijin after PBSpro upgrade

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#50]
The npernode option used -npernode and -npersocket options no longer work on raijin after the latest PBSpro upgrade. The simulation does not run (even -npernode 16) and this appears in mom.out:

```--------------------------------------------------------------------------
Conflicting directives for mapping policy are causing the policy
to be redefined:

  New policy:   bynode
  Prior policy:  BYCORE

Please check that only one policy is defined.
--------------------------------------------------------------------------```

Need to be replace with -map-by.

**Comment by marshallward** [comment]
That's an MPI setting, not PBS.  Are you sure this isn't something else?

Anyway I will have a look.

**Comment by marshallward** [comment]
Are you using openmpi/1.10.1
I don't belive it's been correctly configured yet for Raijin.

**Comment by aidanheerdegen** [comment]
Oh yeah, you're right.

Nope, this is the problem. Kate had runs stopping, as she had an old npernode option. Goes away when she commented it out

**Comment by aidanheerdegen** [comment]
I don't believe she was using openmpi/1.10.1. I reproduced the problem with 1.8.4, and the problem is fixed with this PR.

**Comment by marshallward** [comment]
I think this is not because of PBS, but yes it's happening.

I guess npernode/socket were deprecated anyway so yeah.

Thanks very much for fixing it.

**Comment by marshallward** [comment]
I wonder if switching to -map-by will break older OpenMPI libraries?  And would anyone even notice?

**Comment by marshallward** [comment]
Yeah looks like 1.6.3 does not use -map-by.

I don't know if anyone will ever care, but I guess it is a legitimate "issue" so i'll leave this open.

**Comment by aidanheerdegen** [comment]
Tell them to use an old version of payu for 1.6.3?

**Comment by marshallward** [comment]
Haha, good idea!
Closed!

**Comment by marshallward** [comment]
But seriously... there are too many version assuptions already to take this on.  If it ever comes up then we can reopen this.
