### ISSUE TITLE
runlog default is false

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#55]
Marshall, I thought you'd decided to make runlog default to true?

I would support that change.

**Comment by marshallward** [comment]
Turned on now: f014b0e432121bd32bfe6e2b87e96e9df0b9574b

I recall having some problems when it was enabled, but let's live dangerously and sort them out as they occur.  (I also recall disabling it for some reason on the 0.6 release but I've now forgotten why.)
