### ISSUE TITLE
Input ordering in config.yaml

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#56]
My mom5 run doesn't seem to honour the ordering of inputs in config.yaml as I thought it should.

I've got a bunch of inputs, some of which I want to override others. My reading of the [code which constructs the inputs](https://github.com/marshallward/payu/blob/ddadaf1b5b419f2d1458f5d5a8e44b20892e4705/payu/models/model.py#L187) and the definition of [make_symlink](https://github.com/marshallward/payu/blob/ddadaf1b5b419f2d1458f5d5a8e44b20892e4705/payu/fsops.py#L54) was that later inputs would override those specified earlier.

e.g. this was the input specification I used, as I thought my second directory, which contains `topog.nc` and `ocean_vgrid.nc`, would override those same links from the first directory. This wasn't the case. Am I misunderstanding how this is supposed to work?

```input:
    # Mosaics, grids
    - /short/v45/aph502/mom/input/sis01_mosaic
    # New vgrid and topog
    - /short/v45/aph502/mom/input/sis01_80l
    # Salt restore and other fields
    - /short/v45/aph502/mom/input/sis01
    # CNYF2
    - /short/v45/aph502/mom/input/cnyf2
    # Mask tables
    - /short/v45/aph502/mom/input/sis01_inputs_3600/
    # Restart
    - /short/v45/pas561/mom/archive/mom01v5/restart208/
```

When I switched the ordering of the first two directories it worked as I wanted.

**Comment by marshallward** [comment]
No, I think the first directory has precedence.  First `topog.nc` is linked from input directory 1 into the work directory. Then input directory 2 tests for `topog.nc`, see that it already exists (line 183) then does not do the `make_symlink`.

I don't know why I did it that way, but it was intentional.  Maybe it's dumb though.

**Comment by marshallward** [comment]
Docs also say that earlier directory takes precedence:

**Comment by marshallward** [comment]
BTW I think the original motivation was to protect the original files from contamination but subsequent input entries.

I think the idea would be that you have a "normal" input directory that you might supplement with a restart directory, and that restart directory should not interfere with the "normal" inputs.

I have no attachment to either approach though.  Maybe even a slight preference to let newer directories override the earlier ones.  But it could break runs for other people.

**Comment by aidanheerdegen** [comment]
Sorry, you're right. I misread it. No, if that is the way it is designed and documented then that is fine. It was me who has been at fault the whole time!
