### ISSUE TITLE
CICE inserts dump_last value in namelist, even though this is not a valid variable

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#62]
Because cice namelist error checking is borked 

https://github.com/OceansAus/cice4/issues/4

payu was happily inserting dump_last = .true. into the setup_nml which is not a valid variable for cice4 and was being silently ignored.

**Comment by aidanheerdegen** [comment]
Considering adding support for dump_last into cice4 as it is very useful ...

**Comment by marshallward** [comment]
Probably a good idea, but maybe also make this flag optional?  Like a version check in payu?

I'm probably being too ambitious here, but feels like it would be nice for payu to work on stock CICE.

**Comment by marshallward** [comment]
Or maybe optionally check if the key is present in `setup_nml` before setting the value?

**Comment by aidanheerdegen** [comment]
it works fine with stock cice4, as it cice4 does not properly check namelists, so gets silently ignored. This is a special case of trying to fix some of the stuff in cice4 when I should probably just use cice5, for which this is a valid namelist var.

**Comment by marshallward** [comment]
Does ACCESS-OM still use CICE 4?  (Or should I be asking this off-ticket?)
