### ISSUE TITLE
Modpath manipulation strips too much for some modpaths

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#64]
Stripping the current payu module from the mod path strips too much when there is a double path separator (//) between the path and the module name. 

This is due to a greedy strip operator.

**Comment by marshallward** [comment]
Can you show me the value of `_LMFILES_` or `LOADEDMODULES` ? I'm having trouble reproducing this.  I'm guessing this is due to some particular module with double slashes in it?

**Comment by marshallward** [comment]
Also would `os.path.normpath` help for removing double slashes?

**Comment by marshallward** [comment]
Sorry, I am being dumb, I see now that the problem is with `rstrip` which is not a safe way to truncate the string.  I think your solution is fine, I will merge it.
