### ISSUE TITLE
QGCM cleanup

### ISSUE THREAD

**Issue by marshallward** [marshallward/payu#72]
(For @aidanheerdegen)

Aidan, I am thinking of renaming `mpthreads` to `ompthreads` (if not `threads`) inside the qgcm module.  I don't think "mp" really means anything in the openmp context here.

Also, just as a thought, I am thinking of rewriting the `os.environ.update` as a straight `os.environ[] = ...` expression, which I believe is the preferred method (due to dict overrides).  Do you know of any problems with that?

**Comment by aidanheerdegen** [comment]
Re: `mpthreads`

I think I originally had ompthreads, but for some reason changed it. The only people using it are Andy and Paige. Change it if you want. The whole thing needs some serious attention and is quick hacky to just get it working.

I wonder if there is some value in having a generic mechanism for marking options as deprecated and issuing warnings when they're used, so they can be dropped in future releases? If you agree then I can make an issue for it.

**Comment by aidanheerdegen** [comment]
Re: os.environ.update

No problems whatsoever.

**Comment by marshallward** [comment]
Agree completely on generalising the deprecated settings, we should look into it.

I'll put those changes in, and keep the old `mpthreads` for now.

**Comment by marshallward** [comment]
Changes in 685c81e
