### ISSUE TITLE
Save output/error logs of crashed runs in archive

### ISSUE THREAD

**Issue by marshallward** [marshallward/payu#77]
Currently, we preserve the most recent `.err` and `.out` logs when doing `payu sweep`.  However, a crashed job with many processors can generate very large backtrace logs which can start to fill up one's home directory quickly.

I am proposing here that we no longer preserve these logs, or at least make it conditional.  The original idea here was that people will casually discard useful logs, and we want to keep some record of potential problems, but I don't think this is the way to do it.

**Comment by marshallward** [comment]
BTW seeking feedback from @aidanheerdegen and @nicjhan here!

**Comment by aidanheerdegen** [comment]
It's tricky, as they are potentially useful sources of information. I just went to find one now to satisfy myself that the executable I built was creating stack traces.

There is only ever one copy, which is the last time there was crash, maybe it is sufficient to compress them and then copy them to pbs_logs?

Or create a separate dir (say crash_logs) in archive and put them there?

**Comment by marshallward** [comment]
`crash_logs` is a good idea.  And maybe save it in `/short`?

**Comment by marshallward** [comment]
BTW this might be a more acute problem for me, since my home quota is unbounded and I literally hit disk limit errors rather than quota errors.

**Comment by aidanheerdegen** [comment]
Just bung it in the archive directory? Or were you thinking of keeping multiple crashlogs?

I have had to periodically go and clean up large crash logs.

**Comment by aidanheerdegen** [comment]
Yeah maybe. I only ever look at them to harvest some stats post-fact. Like wall time etc.

Would make it simpler to retain current structure, but just move the directory.

Could just make a link to pbs_logs to retain backwards compatibility

pbs_logs -> archive/pbs_logs

**Comment by aidanheerdegen** [comment]
We (Andy and I) think it would be good to have a "crash-log" option, to keep all the mom.err and mom.out from crashed runs in subdirs of pbs_logs, maybe named for the PBS run-id. It would help a lot when we have a blizzard of errors (which they did over the weekend).

**Comment by marshallward** [comment]
Agreed, I've flagged this for v0.8, will try to make it happen soonish (once Raijin is back up).

**Comment by aidanheerdegen** [comment]
Great.

**Comment by marshallward** [comment]
I have a test mockup in `master`, can you give it a try at some point?

**Comment by marshallward** [comment]
Assuming this works, closing this issue.   Will reopen if I"m wrong!
