### ISSUE TITLE
ACCESS output directory structure

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#79]
Andy isn't convinced about the current method of separating ocean/atmosphere/ice into separate directories.

I know we've had a discussion about this in the past, and I think @marshallward and make @nicjhan were both thinking it should be flattened out.

I thought we should have an issue here to discuss the pros/cons so at least it is documented.

**Comment by aidanheerdegen** [comment]
Does it use more disc space to have the separate?

Or is more complex?

Are there name space issues?

**Comment by marshallward** [comment]
Are we talking about config or output?

**Comment by aidanheerdegen** [comment]
Output.

**Comment by marshallward** [comment]
What are Andy's issues with it?

**Comment by aidanheerdegen** [comment]
I think he found it confusing. Thought new users might find it easier to understand if there were just a bunch of output files in the output directory.

*shrug*

Personally I like it, but like all these things I'm happy to be overruled. Andy is the same BTW, happy to be told current approach is the best.

**Comment by marshallward** [comment]
Namespacing is one issue (what if two models had the same file name?).  It is a lot simpler to have containers for each model and not worry about interference from the other models.

I also prefer the separation, it is logically easier to find, say, a sea ice output if I know it's in the ice directory.  Not all of these files are intuitively named.

I don't think "confusing" is really a good reason to change it.  To not separate them would also be confusing for different reasons.

Happy to talk about it with Andy though, should I come by?  Not like there's much to do today with Raijin down...

**Comment by aidanheerdegen** [comment]
Not sure it is super important. Andy just brought it up so I thought it should be hashed out so the rationale was clear. I agree BTW, and Andy is happy to defer, so I'll say this has been confirmed as desirable behaviour and close this issue.
