### ISSUE TITLE
Default flags for FMS collate

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#80]
The[ default flags for FMS collate](https://github.com/marshallward/payu/blob/master/payu/models/fms.py#L90) are 

'-r -64'

Should we change this to

'-n4 -z -m -r'

which will produce compressed netCDF4 files. The '-m' option uses a sensible missing value rather than zero, which produces weird artefacts in land masked runs.

**Comment by marshallward** [comment]
Yeah good idea

**Comment by marshallward** [comment]
Actually let's wait to talk about compression, I recall some people had
issues with it?

**Comment by aidanheerdegen** [comment]
Regarding collate performance/times, I have not done exhaustive tests, but did try a quarter degree MOM-SIS ocean.nc collation with and without compression (both netcdf4). 

```
Flags         Size        Walltime       Memory
	      (GB)       (hh:mm:ss)      (GB)

-n4 -m	      5.1         00:08:49        5.01
-n4 -m -z     1.5         00:09:13        5.04
-64 -m        5.0         00:09:29        5.01
```
So no change in time or memory required to collate the data, but much reduced file size.

(Note there would normally be a -r flag also, but I did not delete the uncollated files so I could test collation flags)

**Comment by aidanheerdegen** [comment]
There may be no slow-down at all. I noticed a lot of variation when I repeated one of the runs, so the difference may just be noise.

**Comment by marshallward** [comment]
Right... should have read the table more carefully :D

**Comment by marshallward** [comment]
Has this been fixed?  Can I close this?

**Comment by aidanheerdegen** [comment]
Yeah, was changed in this commit

https://github.com/marshallward/payu/commit/0b45346dba08048a3a53b03acb2995284e7a8e1f
