### ISSUE TITLE
broadwell nodes

### ISSUE THREAD

**Issue by AndyHoggANU** [marshallward/payu#83]
I was thinking of testing our ACCESS-OM2 case on the broadwell nodes, to help with getting these small jobs through the queue. But to do this I need to select multiples of 28 cores, rather than 16. When I nominate 28 cores payu asks for 256 by default. Can we modify the logic in this to ensure 28 cores under the normalbw queue?

I'm using the payu/dev module on raijin, btw.

**Comment by marshallward** [comment]
Can you attach your config?  I don't know how 28 could turn into 256.

Also, do you have platform info?

    platform:
        nodesize: 28

**Comment by AndyHoggANU** [comment]
OK, got it -- thanks!! 
I didn't know about the platform: nodesize: option and it was obviously assuming the default nodesize of 16. Will close this issue.

**Comment by marshallward** [comment]
I'll look into automating this.  Some of this info is available via `pbsnodes` and `qstat`, but its not easy to put it all together.
