### ISSUE TITLE
Multiple payu runs per PBS submission 

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#84]
For cheaper models it would be nice to have multiple `payu` runs per PBS submission. Whilst it is possible to simply run the model for longer, there are problems if there is a crash.

This feature has the potential to reduce queuing overhead and so increase throughput, and should be relatively simple to implement.

**Comment by marshallward** [comment]
Yeah, I agree this could be useful, even for larger jobs.

We have discussed this a few times, but no one has prioritised it.

**Comment by aidanheerdegen** [comment]
I volunteered to add it as an issue at the last TWG meeting. TA DAH!
