### ISSUE TITLE
Make collation fails noisy

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/payu#92]
It seems that as currently coded when individual collation jobs fail they don't issue an error or warning to this effect. So users can have an unsuccessful collation and not know it.

In one case collating restart files did not work correctly but the user didn't know, and tried to use those restarts in another run, which failed with many many saturation vapour pressure overflow errors. Presumably due to bad values in some restart fields.

**Comment by marshallward** [comment]
Yeah I dont see any checking of return codes here (assuming it's L132 of fms.py)

**Comment by aidanheerdegen** [comment]
Yeah, it is my fault, I put the multiprocessing code in there.

https://github.com/marshallward/payu/blob/master/payu/models/fms.py#L132

**Comment by aidanheerdegen** [comment]
I thought the error checking here would have done something useful, but it appears not

https://github.com/marshallward/payu/blob/master/payu/models/fms.py#L25

**Comment by marshallward** [comment]
Yes, I tried a few small test codes myself and it's clear that there's more ways to screw this up than to get it right.

Is it necessary to use `multiprocessing` here?  Does it offer an advantage over simply throwing out multiple subprocesses (which admittedly shift the problem to the kernel to handle)?

**Comment by marshallward** [comment]
Is this resolved?  Sadly I'm not really in a position to test it, but I have merged the recent changes into master.

**Comment by aidanheerdegen** [comment]
Yes I believed this was resolved with https://github.com/marshallward/payu/pull/93
